#!/usr/bin/python3
"""Save the current OccupancyGrid as a Nav2-compatible PGM and YAML pair."""

import argparse
import time
from pathlib import Path

import rclpy
from nav_msgs.msg import OccupancyGrid
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, QoSProfile, QoSReliabilityPolicy


class MapReceiver(Node):
    def __init__(self, topic):
        super().__init__("independent_nav_map_saver")
        self.map = None
        qos = QoSProfile(
            depth=1,
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        self.create_subscription(OccupancyGrid, topic, self.callback, qos)

    def callback(self, message):
        self.map = message


def write_map(message, output_base: Path):
    output_base.parent.mkdir(parents=True, exist_ok=True)
    image_path = output_base.with_suffix(".pgm")
    yaml_path = output_base.with_suffix(".yaml")
    width = message.info.width
    height = message.info.height
    pixels = bytearray()
    # OccupancyGrid is bottom-to-top; PGM rows are top-to-bottom.
    for y in range(height - 1, -1, -1):
        for x in range(width):
            occupancy = message.data[y * width + x]
            pixels.append(205 if occupancy < 0 else 0 if occupancy >= 65 else 254)
    with image_path.open("wb") as stream:
        stream.write(f"P5\n# generated by independent_nav_bringup\n{width} {height}\n255\n".encode())
        stream.write(pixels)
    origin = message.info.origin.position
    yaml_path.write_text(
        "image: " + image_path.name + "\n"
        "mode: trinary\n"
        f"resolution: {message.info.resolution}\n"
        f"origin: [{origin.x}, {origin.y}, 0.0]\n"
        "negate: 0\noccupied_thresh: 0.65\nfree_thresh: 0.25\n",
        encoding="utf-8",
    )
    return image_path, yaml_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--output", required=True, help="Map base path without suffix")
    parser.add_argument("--topic", default="/map")
    parser.add_argument("--timeout", type=float, default=15.0)
    args = parser.parse_args()
    rclpy.init()
    receiver = MapReceiver(args.topic)
    deadline = time.monotonic() + args.timeout
    while receiver.map is None and time.monotonic() < deadline:
        rclpy.spin_once(receiver, timeout_sec=0.2)
    if receiver.map is None:
        receiver.destroy_node()
        rclpy.shutdown()
        raise SystemExit(f"No map received from {args.topic} within {args.timeout:.1f} seconds")
    image, yaml = write_map(receiver.map, Path(args.output))
    receiver.get_logger().info(f"Saved {image} and {yaml}")
    receiver.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
